In [1]:
from sqlalchemy import create_engine
import pandas as pd 
import numpy as np
import random
import math 

In [2]:
table_name = 'crypto'
engine = create_engine(f'postgresql://postgres:postgres@localhost:5432/{table_name}')

df_raw = pd.read_sql_query('select * from klines',con=engine)

In [3]:
df_5min = df_raw.query("period_type == '5min'").reset_index()

In [4]:
def get_day_of_week(df):
    """
    Returns the name of the day of the week for the given day number (0-6)
    """
    days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    df['local_numeric_day'] =  df['datetime'].apply(lambda x: (x.weekday()) % 7 + 1)
    df['local_day'] =  df['local_numeric_day'].apply(lambda x: days[x-1])
    return df 


def set_action(df, optimum_sell_rewards=15, optimum_buy_rewards=15):
    """
    Adds a new column called 'price_diff' to the given DataFrame,
    containing the difference between the current row's close price and
    the previous row's close price.
    """
    # Create a new column called 'prev_close' that contains the close price from the previous row
    df['prev_close'] = df['close'].shift(1)

    # Compute the difference between the current row's close price and the previous row's close price
    df['price_diff'] = df['close'] - df['prev_close']
    df['sell_rewards'] = df['price_diff'].shift(-1)
    df['buy_rewards'] = (df['price_diff'].shift(-1))*-1
    df['sell_cumulative_rewards'] = df['sell_rewards'].cumsum()
    df['buy_cumulative_rewards'] = df['buy_rewards'].cumsum()
    df['actions'] = -1 # default 0 = buy, 1 = sell, -1 = no action
    df.loc[df['buy_rewards'] >= 5, 'actions'] = 0
    df.loc[df['sell_rewards'] > 5 , 'actions'] = 1
    df.loc[df['actions'] == 1, 'one_time_reward'] = df['sell_rewards']
    df.loc[df['actions'] == 0, 'one_time_reward'] = df['buy_rewards']
    df.loc[df['actions'] == -1, 'one_time_reward'] = 0

    # Return the updated DataFrame
    return df


# normal distribution optimum bin
def get_optimal_normal_distribution_num_bins(df):
    """
    Estimates the optimal number of bins for the 'volume_trade' column
    of the given DataFrame using the Freedman-Diaconis rule, and returns
    the estimated number of bins.
    """
    # Compute the interquartile range of the 'volume_trade' column
    q1, q3 = np.percentile(df['volume_trade'], [25, 75])
    iqr = q3 - q1

    # Estimate the optimal bin width using the Freedman-Diaconis rule
    bin_width = 2 * iqr / np.cbrt(len(df))

    # Compute the estimated number of bins
    num_bins = int(np.ceil((df['volume_trade'].max() - df['volume_trade'].min()) / bin_width))

    # Return the estimated number of bins
    return num_bins


# power law optimum bin 
def get_optimal_pareto_distribution_num_bins(df):
    """
    Estimates the optimal number of bins for the 'volume_trade' column
    of the given DataFrame using the Sturges method for power law distributions,
    and returns the estimated number of bins.
    """
    # Compute the sample size and the maximum value of the 'volume_trade' column
    n = len(df['amount'])
    x_max = df['amount'].max()

    # Estimate the optimal number of bins using the Sturges method
    num_bins = int(np.ceil(np.log2(n) + np.log2(1 + x_max)))

    # Return the estimated number of bins
    return num_bins

def pareto_distribution_bins(df, num_bins):
    """Creates power law bins for the 'volume_trade' column of the given
    DataFrame using the qcut function, and returns the updated DataFrame.
    """
    # Compute the quantiles of the 'volume_trade' column using a power law distribution
    quantiles = pd.qcut(df['amount'], num_bins, labels=False, duplicates='drop')

    # Add a new column to the DataFrame with the bin labels
    df['volume_bins'] = quantiles

    # Return the updated DataFrame
    return df


def encode_time(df):
    """Encodes the time in the given DataFrame as a string representing the time
    in sequential order (hour-minute-second), and returns the updated DataFrame.
    """
    # Convert the 'time' column to a datetime object
    df['time'] = pd.to_datetime(df['datetime'])
    df['date'] = df['datetime'].dt.date

    # Extract the hour, minute, and second from the 'time' column
    df['hour'] = df['time'].dt.hour
    df['minute'] = df['time'].dt.minute
    df['second'] = df['time'].dt.second

    # Convert the hour, minute, and second to strings
    df['hour_str'] = df['hour'].astype(str).str.zfill(2)
    df['minute_str'] = df['minute'].astype(str).str.zfill(2)
    df['second_str'] = df['second'].astype(str).str.zfill(2)

    # Concatenate the hour, minute, and second strings into a single time string
    df['encoded_time'] = df['hour_str'] + '-' + df['minute_str'] + '-' + df['second_str']

    # Drop the original hour, minute, and second columns
    df = df.drop(['hour', 'minute', 'second', 'hour_str', 'minute_str', 'second_str'], axis=1)

    # Return the updated DataFrame with the encoded time string
    return df


In [5]:
df_5min = get_day_of_week(df_5min)
df_5min = set_action(df_5min)
df_5min = pareto_distribution_bins(df_5min, get_optimal_pareto_distribution_num_bins(df_5min))
df_5min = encode_time(df_5min)
df_5min.head()

level_0  index          id     open    close     high      low   
0   237059      0  1672502400  1202.89  1202.79  1203.14  1202.79  \
1   237060      1  1672502700  1202.79  1202.64  1202.86  1202.60   
2   237061      2  1672503000  1202.64  1202.32  1202.64  1202.21   
3   237062      3  1672503300  1202.20  1202.00  1202.20  1201.00   
4   237063      4  1672503600  1201.95  1203.22  1203.41  1201.95   

             vol     amount period_type  ... prev_close price_diff   
0    1304.147073   1.084000        5min  ...        NaN        NaN  \
1   19612.445390  16.306101        5min  ...    1202.79      -0.15   
2   27485.863219  22.856000        5min  ...    1202.64      -0.32   
3  106878.352877  88.951166        5min  ...    1202.32      -0.32   
4  102618.915554  85.315059        5min  ...    1202.00       1.22   

  sell_rewards buy_rewards  sell_cumulative_rewards buy_cumulative_rewards   
0        -0.15        0.15                    -0.15                   0.15  \
1        -0.32        0.32                    -0.47                   0.47   
2        -0.32        0.32                    -0.79                   0.79   
3         1.22       -1.22                     0.43                  -0.43   
4        -0.20        0.20                     0.23                  -0.23   

   actions  one_time_reward  volume_bins  encoded_time  
0       -1              0.0            0      00-00-00  
1       -1              0.0            7      00-05-00  
2       -1              0.0           10      00-10-00  
3       -1              0.0           23      00-15-00  
4       -1              0.0           23      00-20-00  

[5 rows x 26 columns]

In [13]:
df_5min.shape

(42912, 26)

In [15]:
df = df_5min.copy()

In [16]:
# Define the state space
num_days = df['local_numeric_day'].nunique()
num_times = df['time'].nunique()
num_volume_bins = df['volume_bins'].nunique()
state_space = np.zeros((num_days, num_times))
train_split = 0.8


# Define the action space
num_action = df['actions'].nunique()
action_space = np.zeros((num_volume_bins, num_action))


# Initialize the Q-values
global Q_star 


# Initialize learning rate, discount factor, exploration
alpha = 0.1
gamma = 0.9
epsilon = 0.1

In [17]:
# Define the reward function
def reward(price_rewards):
    return price_rewards


# Define a function to get the current state
def get_state(day, time, volume_bins, action):
    # concatenate scalar values into a numpy array
    state = np.array((time, day, volume_bins, action))
    print("Get state:", type(state), state.shape, state, state[0], state[1], state[2], state[3])
    return state


def choose_action(state):
    print("Choose action state:", type(state), state, state.shape)
    if random.uniform(0, 1) < epsilon:
        # Randomly choose an action
        action = np.random.choice((0, num_action-1))
    else:
        # Choose the action with highest Q value
        action = np.argmax(Q[state[0]][state[1]][state[2]])
    return action


# Generate the sample data
def generate_sample(df):

    cols = ['local_numeric_day', 'encoded_time', 'volume_bins', 'actions']
    df = df[cols]

    # Get states as tuple
    state_tuple = create_state_tuple(df)

    # Initiate Q table 
    global Q_star 
    Q_star = np.zeros((state_tuple))

    train_data = df[:math.floor(df.shape[0]*train_split)].to_numpy()
    test_data = df[train_data.shape[0]:].to_numpy()

    return train_data, test_data


def train_sarsa(train_data):
    # Define variables to track performance validation
    prev_avg_reward = -1000
    avg_reward = 0
    num_episodes = 0
    
    # Train for multiple episodes until convergence
    while abs(avg_reward - prev_avg_reward) > 0.001:
        prev_avg_reward = avg_reward
        total_reward = 0
        print("Start SARSA")
        
        # Loop through all training data
        for i in range(len(train_data)-1):
            # Get current state and action
            state = get_state(train_data[i][0], train_data[i][1], train_data[i][2], train_data[i][3])
            # action = choose_action(state)
            
            # Get next state and reward
            # next_state = get_state(train_data[i+1][0], train_data[i+1][1], train_data[i+1][2], train_data[i+1][3])
            reward = train_data[i+1][-1] * 0.1
            
            # Choose next action based on epsilon-greedy policy
            # next_action = choose_action(next_state)
            
            # Update Q table
            td_error = reward + gamma * Q[i+1][-1][-1] - Q[i][-1][-1]
            Q[i][-1][-1] += alpha * td_error
        
            total_reward += reward
        
        # Calculate average reward for the current episode
        avg_reward = total_reward / len(train_data)
        num_episodes += 1
        print("Episode:", num_episodes, "Average Reward:", avg_reward)
    
    return Q


def create_state_tuple(df_train):
    '''
    Automatically initiate state tuple based on the number of unique
    values in each state (features) from the given dataframe to ease the initiation of Q table
    '''
    state_list = []

    state_list.append(df_train.shape[0])
    for col in df_train:
        state_list.append(df_train[col].nunique())

    state_tuple = tuple(state_list)

    return state_tuple

In [18]:
train_data, test_data = generate_sample(df)

MemoryError: Unable to allocate 56.1 GiB for an array with shape (42912, 7, 288, 29, 3) and data type float64

In [19]:
rewards = df['one_time_reward'].to_list()

In [20]:
import SARSA_one_state as SARSA

In [21]:
num_states = df['encoded_time'].nunique()
num_actions = df['actions'].nunique()
lr = 0.005
discount_factor = 0.9
epsilon = 0.5
num_episodes = 10000000
num_steps_per_episode = 10
total_rewards = 0
GAMMA = 0.9
print(num_states, num_actions)

sarsa_agent = SARSA.SARSAAgent(
    df,
    learning_rate=lr,
    discount_factor=discount_factor,
    epsilon=epsilon
)

global Q 
sarsa_agent.initialize_q_table(df)
Q = sarsa_agent.q_table
reward_table = sarsa_agent.reward_table

288 3
[[-2.50402685e-01  2.50402685e-01  0.00000000e+00]
 [-7.28859060e-02  7.28859060e-02  0.00000000e+00]
 [-2.76577181e-01  2.76577181e-01  0.00000000e+00]
 [-3.81543624e-01  3.81543624e-01  0.00000000e+00]
 [-6.74496644e-02  6.74496644e-02  0.00000000e+00]
 [-3.72080537e-01  3.72080537e-01  0.00000000e+00]
 [-7.81879195e-02  7.81879195e-02  0.00000000e+00]
 [ 4.33892617e-01 -4.33892617e-01  0.00000000e+00]
 [ 7.99328859e-02 -7.99328859e-02  0.00000000e+00]
 [ 2.02013423e-02 -2.02013423e-02  0.00000000e+00]
 [-2.94630872e-02  2.94630872e-02  0.00000000e+00]
 [ 2.77114094e-01 -2.77114094e-01  0.00000000e+00]
 [ 3.88255034e-01 -3.88255034e-01  0.00000000e+00]
 [ 1.62416107e-01 -1.62416107e-01  0.00000000e+00]
 [-5.67919463e-01  5.67919463e-01  0.00000000e+00]
 [-1.11543624e-01  1.11543624e-01  0.00000000e+00]
 [ 3.68724832e-01 -3.68724832e-01  0.00000000e+00]
 [-7.42953020e-02  7.42953020e-02  0.00000000e+00]
 [ 3.44832215e-01 -3.44832215e-01  0.00000000e+00]
 [ 8.53020134e-02 -8.5302

In [24]:
reward_table.shape

(288, 3)

In [22]:
action_dict = {
	'buy': 0,
	'sell': 1,
	'no_action': 2
}


def policy(Q, sarsa_agent, state, epsilon = 0.1, verbose = False) -> (int, float): 
	best_action = None
	best_value = float('-inf')
	
	# update allowed actions everytime based on agent current holding unit 
	if sarsa_agent.isHolding == False: # indicate can buy/no action but cannot sell
		allowed_actions = ['buy', 'no_action']
	else:
		allowed_actions = ['sell', 'no_action']

	random.shuffle(allowed_actions)

	for action in allowed_actions:
		if verbose:
			print(f"Holding: {sarsa_agent.isHolding}")
			print(f'action: {action}')
			print(f'value: {Q[state][action_dict.get(action)]} vs best_value: {best_value}')
			print(f'new best action: {action}')
		if Q[state][action_dict.get(action)] > best_value:
			best_action = action_dict.get(action)
			best_value = Q[state][best_action] 
				
	
	r_var = random.random()
	if r_var < epsilon:
		if verbose:
			print(f'Choosing random action')
		best_action = action_dict.get(random.choice(allowed_actions))
		best_value = Q[state][best_action]
		
	if verbose:
		print(f'Final action: {best_action}\n')

	return best_action, best_value


# Update Q-value for a state-action pair based on observed rewards and estimated future Q-values
def update_q_value(state, action, reward, next_state, next_action, verbose=False):
    
    if verbose == True:
	    print(f"State: {state}, Action: {action}, Rewards: {reward}, Next_state: {next_state}, Next_action: {next_action}")
    # Check if the (state, action) pair exists in the Q-table
    # if (state, action) not in Q:
    #     Q[(state, action)] = 0.0
    
    # Compute the updated Q-value using the SARSA update equation
    current_q = Q[state, action_dict.get(action)]
    next_q = Q[next_state, action_dict.get(next_action)]
    new_q = current_q + lr * (reward + GAMMA * next_q - current_q)
    
    # Update the Q-value in the Q-table
    Q[state, action_dict.get(action)] = new_q

In [23]:
# Training loop
# for episode in range(num_episodes):
steps = []  
rewards_list = []
steps_list = []

for episode in range(num_episodes):
    current_state = 0  # Starting state
    action, action_value = policy(Q, sarsa_agent, current_state, epsilon)
    # update upcoming allowed actions
    if action == 0:
        sarsa_agent.isHolding = True
    if action == 1:
        sarsa_agent.isHolding = False
    total_rewards = 0

    while (current_state != Q.shape[0] - 1):
        rewards = reward_table[current_state][action]
        total_rewards += rewards
        steps.append(action)
        next_state = current_state + 1 
        next_action, next_action_value = policy(Q, sarsa_agent, next_state, epsilon)
        update_q_value(current_state, action, rewards, next_state, next_action)

        # print(f'After update:, action: {action}, action_value : {action_value}, next_action: {next_action}, next_action_value: {next_action_value}\n')
        # update upcoming allowed actions
        if next_action == 0:
            sarsa_agent.isHolding = True
        if next_action == 1:
            sarsa_agent.isHolding = False

        current_state = next_state
        action = next_action 
        action_value = next_action_value

    rewards_list.append(total_rewards)
    steps_list.append(steps)

KeyboardInterrupt: 

In [ ]:
df_check = pd.DataFrame(rewards_list, columns=['rewards'])
df_check.describe()

In [ ]:
Q

In [ ]:
# Check if each row has different values
is_different = np.all(np.diff(Q, axis=1), axis=1)

# Display the result
print(is_different)